# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 797ff887f90e78e2732732abf95dc274c35b39421344f769431317c39f671eddfb51bc06ca02dfa468fb1dfff10b5ac9e393cb554a78b5e348b72b34b9d4e8c6

test:
  secret_key_base: 0611a4e74100a2097d862da0cd1ed929000d6935170d4868b6cd09ac501d99dc6eaf8099e0c82f362d7ca42b19d97ee3aac87e536b1e6d5d80b360ab607244eb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
